#!/usr/bin/env python3
"""Regenerate src/translators-generated.hpp from Crowdin's "Top Members" report.

Crowdin is the source of truth for translator credits: this rewrites the
whole generated array, so a name hand-added to the .hpp will be dropped on
the next run. Requires CROWDIN_PERSONAL_TOKEN and CROWDIN_PROJECT_ID in the
environment (the same secrets .github/workflows/crowdin.yml already uses).
"""

import argparse
import collections
import json
import os
import re
import sys
import time
import urllib.error
import urllib.request

API_BASE = "https://api.crowdin.com/api/v2"
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

HEADER_TEMPLATE = """\
// GENERATED FILE - do not edit by hand.
//
// Regenerated by .github/scripts/update-translators.py from Crowdin's "Top
// Members" report every time .github/workflows/crowdin.yml runs. Hand edits
// will be overwritten on the next sync.

#pragma once

#include <QStringList>

inline const QStringList ptz_translator_credits = {{
{entries}}};
"""

AUTHORS_SECTION_RE = re.compile(r"(?<=^Translators:\n)(?: .*\n)+", re.MULTILINE)


def api(method, path, token, payload=None):
    url = f"{API_BASE}{path}"
    data = json.dumps(payload).encode() if payload is not None else None
    headers = {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}
    req = urllib.request.Request(url, data=data, headers=headers, method=method)
    try:
        with urllib.request.urlopen(req, timeout=90) as resp:
            return json.loads(resp.read().decode())
    except urllib.error.HTTPError as err:
        sys.exit(f"Crowdin API {method} {path} failed: {err.code} {err.read().decode(errors='replace')}")


def source_ini_basename():
    """The source locale filename crowdin.yml declares, so we never credit it as a translation."""
    text = open(os.path.join(ROOT, "crowdin.yml"), encoding="utf-8").read()
    match = re.search(r'"source":\s*"([^"]+)"', text)
    if not match:
        sys.exit("could not find a \"source\" entry in crowdin.yml")
    return os.path.basename(match.group(1))


def shipped_locales(locale_dir, source_basename):
    """Locale codes we actually ship, derived from data/locale/*.ini filenames."""
    locales = set()
    for name in os.listdir(locale_dir):
        if name == source_basename or not name.endswith(".ini"):
            continue
        locales.add(name[: -len(".ini")])
    return locales


def get_me(token):
    return api("GET", "/user", token)["data"]


def get_target_languages(token, project_id):
    """locale -> language display name, for the project's configured target languages."""
    project = api("GET", f"/projects/{project_id}", token)["data"]
    return {lang["locale"]: lang["name"] for lang in project["targetLanguages"]}, {
        lang["id"]: lang["locale"] for lang in project["targetLanguages"]
    }


def generate_report(token, project_id):
    payload = {"name": "top-members", "schema": {"unit": "words", "format": "json"}}
    created = api("POST", f"/projects/{project_id}/reports", token, payload)
    return created["data"]["identifier"]


def wait_for_report(token, project_id, report_id, timeout=300):
    deadline = time.time() + timeout
    while time.time() < deadline:
        status = api("GET", f"/projects/{project_id}/reports/{report_id}", token)["data"]
        if status["status"] == "finished":
            return
        if status["status"] in ("failed", "canceled"):
            sys.exit(f"Crowdin report {report_id} ended as {status['status']}")
        time.sleep(5)
    sys.exit(f"Crowdin report {report_id} did not finish within {timeout}s")


def download_report(token, project_id, report_id):
    url = api("GET", f"/projects/{project_id}/reports/{report_id}/download", token)["data"]["url"]
    with urllib.request.urlopen(url, timeout=60) as resp:
        return json.loads(resp.read().decode())["data"]


def escape(name):
    return name.replace("\\", "\\\\").replace('"', '\\"')


def collect_credits(members, lang_id_to_locale, locale_to_name, allowed_locales, exclude_username, min_words):
    """locale -> [(translated_words, display_string), ...], most-contributed first."""
    by_locale = collections.defaultdict(list)
    for member in members:
        translated = member.get("translated") or 0
        if translated < min_words:
            continue
        user = member.get("user") or {}
        username = (user.get("username") or "").lower()
        if not username or username == exclude_username:
            continue
        full_name = user.get("fullName") or user.get("username")
        for lang in member.get("languages", []):
            locale = lang_id_to_locale.get(lang["id"])
            if locale is None or locale not in allowed_locales:
                continue
            language_name = locale_to_name.get(locale, lang.get("name", lang["id"]))
            by_locale[locale].append((translated, f"{full_name} ({language_name})"))

    for locale, entries in by_locale.items():
        entries.sort(key=lambda e: (-e[0], e[1]))

    return by_locale


def flatten(by_locale):
    """Display strings in the same order they're written to the .hpp: grouped by locale
    (alphabetically), most-contributed first within each locale."""
    return [display for locale in sorted(by_locale) for _, display in by_locale[locale]]


def render(by_locale):
    lines = [f'\t"{escape(display)}",\n' for display in flatten(by_locale)]
    return HEADER_TEMPLATE.format(entries="".join(lines))


def write_if_changed(path, content):
    changed = not os.path.exists(path) or open(path, encoding="utf-8").read() != content
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    return changed


def update_authors(path, by_locale):
    """Rewrite only the Translators: block, so the rest of the hand-formatted file keeps its shape."""
    text = open(path, encoding="utf-8").read()
    block = "".join(f" {display}\n" for display in flatten(by_locale))
    updated, count = AUTHORS_SECTION_RE.subn(lambda _: block, text, count=1)
    if count != 1:
        sys.exit(f"expected exactly one Translators: block in {path}, found {count}")
    return write_if_changed(path, updated)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default=os.path.join(ROOT, "src", "translators-generated.hpp"))
    parser.add_argument("--authors-file", default=os.path.join(ROOT, "AUTHORS"))
    parser.add_argument("--locale-dir", default=os.path.join(ROOT, "data", "locale"))
    parser.add_argument("--min-words", type=int, default=10, help="minimum words translated to earn credit")
    args = parser.parse_args()

    token = os.environ.get("CROWDIN_PERSONAL_TOKEN")
    project_id = os.environ.get("CROWDIN_PROJECT_ID")
    if not token or not project_id:
        sys.exit("set CROWDIN_PERSONAL_TOKEN and CROWDIN_PROJECT_ID")

    allowed_locales = shipped_locales(args.locale_dir, source_ini_basename())
    locale_to_name, lang_id_to_locale = get_target_languages(token, project_id)
    exclude_username = (get_me(token).get("username") or "").lower()

    report_id = generate_report(token, project_id)
    wait_for_report(token, project_id, report_id)
    members = download_report(token, project_id, report_id)

    by_locale = collect_credits(
        members, lang_id_to_locale, locale_to_name, allowed_locales, exclude_username, args.min_words
    )
    if not by_locale:
        sys.exit("Crowdin returned no credited translators for any shipped locale; refusing to empty the file")

    total = sum(len(v) for v in by_locale.values())

    hpp_changed = write_if_changed(args.out, render(by_locale))
    print(f"{'Updated' if hpp_changed else 'Unchanged'} {args.out}: {total} credits across {len(by_locale)} locales")

    authors_changed = update_authors(args.authors_file, by_locale)
    print(f"{'Updated' if authors_changed else 'Unchanged'} {args.authors_file}: {total} credits")


if __name__ == "__main__":
    main()
