#!/usr/bin/env python3
"""Regenerate src/contributors-generated.hpp and AUTHORS from git history.

Run manually (no network access needed - it only reads local git history):

    scripts/update-contributors.py

Counts commit authors on --ref (default: main) that aren't also reachable
from --exclude-ref (default: template/master, obsproject/obs-plugintemplate's
history as merged into this repo - its authors aren't obs-ptz contributors),
after .mailmap canonicalization, excluding --exclude-email addresses
(default: Crowdin's bot account - not a code contribution). Add a name that
shares a real contributor's email or spelling variant to .mailmap rather
than teaching this script about it.

The project maintainer (MAINTAINER_EMAIL below) is excluded from
src/contributors-generated.hpp only, since the About dialog already credits
them separately as "By: ...". AUTHORS has no such separate credit, so it
still lists them among the contributors, as it always has.

--exclude-ref can't catch a commit that was cherry-picked from the template
rather than merged - it gets a new SHA on `main`, so it's never "reachable
from" the branch it was picked from, even though it's the same template
maintenance work. List those individually, one full SHA per line, in
scripts/update-contributors-exclude.txt (or pass --exclude-commit), rather
than excluding the whole author: they may have other, real contributions
too.
"""

import argparse
import collections
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_EXCLUDE_COMMITS_FILE = os.path.join(ROOT, "scripts", "update-contributors-exclude.txt")

MAINTAINER_EMAIL = "grant.likely@secretlab.ca"  # credited separately as "By: Grant Likely" in the About dialog

DEFAULT_EXCLUDE_EMAILS = {
    "support+bot@crowdin.com",  # Crowdin Bot: translation-sync commits, not code contributions
}

HEADER_TEMPLATE = """\
// GENERATED FILE - do not edit by hand.
//
// Regenerated by scripts/update-contributors.py from git history. Hand
// edits will be overwritten on the next run. To fix a name or merge a
// duplicate identity, edit .mailmap instead and re-run the script.

#pragma once

#include <QStringList>

inline const QStringList ptz_code_contributors = {{
{entries}}};
"""

AUTHORS_SECTION_RE = re.compile(r"(?<=^Contributors:\n)(?: .*\n)+", re.MULTILINE)


def resolve_ref(ref):
    result = subprocess.run(
        ["git", "rev-parse", "--verify", "--quiet", ref],
        cwd=ROOT,
        capture_output=True,
        text=True,
    )
    return result.stdout.strip() if result.returncode == 0 else None


def load_excluded_commits(path, extra):
    shas = list(extra)
    if path and os.path.exists(path):
        for line in open(path, encoding="utf-8"):
            line = line.split("#", 1)[0].strip()
            if line:
                shas.append(line)

    resolved = set()
    for sha in shas:
        full = resolve_ref(sha)
        if full is None:
            sys.exit(f"--exclude-commit / {path}: {sha!r} does not resolve to a commit")
        resolved.add(full)
    return resolved


def commit_authors(ref, exclude_refs, exclude_commits):
    valid_excludes = []
    for exclude_ref in exclude_refs:
        if resolve_ref(exclude_ref):
            valid_excludes.append(exclude_ref)
        else:
            print(f"warning: --exclude-ref {exclude_ref!r} does not resolve; not excluding it", file=sys.stderr)

    revs = [ref] + (["--not", *valid_excludes] if valid_excludes else [])
    out = subprocess.run(
        ["git", "log", "--no-merges", "--format=%H\t%aN\t%aE", *revs],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout

    counts = collections.Counter()
    seen_excluded = set()
    for line in out.splitlines():
        sha, name, email = line.split("\t", 2)
        if sha in exclude_commits:
            seen_excluded.add(sha)
            continue
        counts[(name, email)] += 1

    for sha in sorted(exclude_commits - seen_excluded):
        print(f"warning: excluded commit {sha} is not reachable from {ref}; check it's still needed", file=sys.stderr)

    return [(count, name, email) for (name, email), count in counts.items()]


def escape(name):
    return name.replace("\\", "\\\\").replace('"', '\\"')


def render(entries):
    lines = [f'\t"{escape(name)}",\n' for _, name, _ in entries]
    return HEADER_TEMPLATE.format(entries="".join(lines))


def write_if_changed(path, content):
    changed = not os.path.exists(path) or open(path, encoding="utf-8").read() != content
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    return changed


def update_authors(path, entries):
    """Rewrite only the Contributors: block, so the rest of the hand-formatted file keeps its shape."""
    text = open(path, encoding="utf-8").read()
    block = "".join(f" {name}\n" for _, name, _ in entries)
    updated, count = AUTHORS_SECTION_RE.subn(lambda _: block, text, count=1)
    if count != 1:
        sys.exit(f"expected exactly one Contributors: block in {path}, found {count}")
    return write_if_changed(path, updated)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--ref", default="main", help="git ref to count contributions on (default: main)")
    parser.add_argument(
        "--exclude-ref",
        action="append",
        default=None,
        help="exclude commits reachable from this ref (repeatable; default: template/master)",
    )
    parser.add_argument(
        "--exclude-commit",
        action="append",
        default=[],
        help="additional commit SHA to exclude (repeatable); merged with --exclude-commits-file",
    )
    parser.add_argument(
        "--exclude-commits-file",
        default=DEFAULT_EXCLUDE_COMMITS_FILE,
        help="file of commit SHAs to exclude, one per line, '#' comments allowed "
        "(default: scripts/update-contributors-exclude.txt; pass '' to skip it)",
    )
    parser.add_argument("--out", default=os.path.join(ROOT, "src", "contributors-generated.hpp"))
    parser.add_argument("--authors-file", default=os.path.join(ROOT, "AUTHORS"))
    parser.add_argument(
        "--exclude-email",
        action="append",
        default=[],
        help="additional email to exclude (repeatable, from both outputs); merged with the built-in defaults",
    )
    args = parser.parse_args()

    exclude_refs = args.exclude_ref if args.exclude_ref is not None else ["template/master"]
    exclude_commits = load_excluded_commits(args.exclude_commits_file, args.exclude_commit)
    exclude = DEFAULT_EXCLUDE_EMAILS | {e.lower() for e in args.exclude_email}

    entries = [
        e for e in commit_authors(args.ref, exclude_refs, exclude_commits) if e[2].lower() not in exclude
    ]
    if not entries:
        sys.exit("no contributors left after exclusions; refusing to empty the file")

    # Matches the old scripts/update-authors.sh's `sort -nr`: ties in count fall back to
    # a reversed whole-line comparison, i.e. reverse-alphabetical by name. Python's sort
    # is stable, so pre-sorting by name descending and then re-sorting by count
    # descending reproduces that tie order.
    entries.sort(key=lambda e: e[1], reverse=True)
    entries.sort(key=lambda e: e[0], reverse=True)

    width = max(len(str(count)) for count, _, _ in entries)
    for count, name, _ in entries:
        print(f"{count:>{width}}  {name}")

    hpp_entries = [e for e in entries if e[2].lower() != MAINTAINER_EMAIL]
    if not hpp_entries:
        sys.exit(f"no contributors left for {args.out} after excluding the maintainer; refusing to empty it")
    hpp_changed = write_if_changed(args.out, render(hpp_entries))
    print(f"{'Updated' if hpp_changed else 'Unchanged'} {args.out}: {len(hpp_entries)} contributors")

    authors_changed = update_authors(args.authors_file, entries)
    print(f"{'Updated' if authors_changed else 'Unchanged'} {args.authors_file}: {len(entries)} contributors")


if __name__ == "__main__":
    main()
