// GENERATED FILE - do not edit by hand.
//
// Regenerated by scripts/update-contributors.py from git history. Hand
// edits will be overwritten on the next run. To fix a name or merge a
// duplicate identity, edit .mailmap instead and re-run the script.

#pragma once

#include <QStringList>

// clang-format off
inline const QStringList ptz_code_contributors = {
	"Fabio Ferrari",
	"Norihiro Kamae",
	"Luuk Verhagen",
	"Trouffman",
	"Kaito Udagawa",
	"Jonatã Bolzan Loss",
	"Eddy Weiz",
	"Jim Hauxwell",
	"Jason Lanclos",
	"Eric Schmidt",
	"BitRate27",
	"Anthony Roberts",
};
// clang-format on
