// GENERATED FILE - do not edit by hand.
//
// Regenerated by .github/scripts/update-translators.py from Crowdin's "Top
// Members" report every time .github/workflows/crowdin.yml runs. Hand edits
// will be overwritten on the next sync.

#pragma once

#include <QStringList>

inline const QStringList ptz_translator_credits = {
	"<b>Danish</b>",
	"ETE-Design",
	"<b>German</b>",
	"Normen Hansen (normenh)",
	"<b>Spanish</b>",
	"alanfermtz",
	"<b>French</b>",
	"arthur_fr",
	"<b>Italian</b>",
	"Giuseppe Chiodaroli (sky7176)",
	"<b>Korean</b>",
	"Lee Jihaeng (jh-studio)",
	"<b>Dutch</b>",
	"Manoah Tervoort (mtdvlpr)",
	"<b>Norwegian</b>",
	"John Hanssen Kolstad (johnhanssen)",
	"<b>Portuguese, Brazilian</b>",
	"Cássio Petry (cassiopetry)",
	"luca montibeller nunes (NosnafitaBR)",
	"<b>Portuguese</b>",
	"danvoulez",
};
