// GENERATED FILE - do not edit by hand.
//
// Regenerated by .github/scripts/update-translators.py from Crowdin's "Top
// Members" report every time .github/workflows/crowdin.yml runs. Hand edits
// will be overwritten on the next sync.

#pragma once

#include <QStringList>

inline const QStringList ptz_translator_credits = {
	"cassiopetry (Portuguese, Brazilian)",
	"ETE-Design (Danish)",
	"Manoah Tervoort (Dutch)",
	"이지행 (Korean)",
	"Norman Hansen (German)",
	"Giuseppe Chiodaroli (Italian)",
	"arthur_fr (French)",
	"alanfermtz (Spanish)",
	"John Hanssen Kolstad (Norwegian)",
	"danvoulez (Portuguese)",
	"Luca Montibeller Nunes (Portuguese, Brazilian)",
	"Valdinel Lankewicz (Portuguese)",
};
